controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Jumps < 2) {
        Dune_Runner.vy = -325
        Jumps += 1
    }
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Player, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    pause(1000)
})
sprites.onCreated(SpriteKind.Projectile, function (sprite) {
    sprite.setPosition(168, randint(35, 111))
    sprite.ax = -190
})
let Scap: Sprite = null
let Dune_Runner: Sprite = null
let Jumps = 0
Jumps = 0
game.splash("You are the", "Dune Runner")
game.splash("Run Against the Wind")
game.splash("Or Die Trying...")
info.setLife(5)
scene.setBackgroundColor(9)
Dune_Runner = sprites.create(assets.image`The DuneRunner`, SpriteKind.Player)
Dune_Runner.setStayInScreen(true)
Dune_Runner.ay = 1250
Dune_Runner.ax = -500
controller.moveSprite(Dune_Runner, 50, 0)
forever(function () {
    if (Dune_Runner.y > 111) {
        Jumps = 0
    }
})
forever(function () {
    info.changeScoreBy(1)
    pause(500)
})
forever(function () {
    if (true) {
    	
    }
})
game.onUpdateInterval(500, function () {
    if (randint(0, 1) == 0) {
        Scap = sprites.create(img`
            ...................
            ...............e...
            ...............ee..
            .............ee4e..
            .......eeeeeee44e..
            ......ee44444444e..
            ....ee4444444444e..
            ....e44444444442e..
            ...e444444444422e..
            .eee444444222222e..
            .e44444222222224ee.
            .ee22222222244444e.
            e..e4222244444444e.
            ....e44444444444ee.
            ....ee4444444444e..
            .....e44444444ee...
            .....e44444eeee....
            .....e4eeee........
            .....eee...........
            `, SpriteKind.Projectile)
    } else if (randint(0, 2) == 1) {
        Scap = sprites.create(img`
            .....................e..
            ....................e...
            .................eeee...
            ...............eeebbe...
            ..............eebbbe..e.
            ............eebbaae..e..
            ..........eebbbabee..e..
            .........eebabbaae..ee..
            ......eeebbbbabbeeeebe..
            e.eeeebbbbabbabbbabbbe..
            .ebbbbbbbabbbbabbaabbe..
            .ebbbbbababbbbabbbabee..
            .ebbabbabababbabbbabe...
            ..ebabbabbabbbbabbbbe...
            ..ebabaabbaababbbbbe....
            ..ebbabaabbaabbbbbe.....
            ...ebabbbabbbbbbee......
            ...ebaabbbbbeeeee.......
            ...ebbaabbbbe...........
            ....ebbbbbbbbe..........
            ....ebbbbbbbbee.........
            ....eebbbbbbbbbe........
            .....eeeeeeebbbbe.e.....
            ............eeeeee......
            `, SpriteKind.Projectile)
    } else if (randint(0, 2) == 2) {
        Scap = sprites.create(img`
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ...................................fff..
            ..................................fffff.
            .................................f..fff.
            .............ffffffff................ff.
            .........ffffffffffffff.............fff.
            ....fffffffffffffffffffff..........ffff.
            .ff2ffffffffffffffffffffffff......ffff..
            .fffff2ffffffff...ffffffffffffffffffff..
            .ffffffffff...........fffffffffffffff...
            ..fffffff..................ffffffff.....
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            `, SpriteKind.Projectile)
    } else {
        Scap = sprites.create(img`
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ............111...............
            ............1..1..............
            ......111....111..............
            ......1.11..1111..............
            ......1.111111111.............
            .......1111111111.............
            .......11111111111............
            ........11111111111...........
            .........111111111............
            ..........1111111.............
            ............1111..............
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            `, SpriteKind.Projectile)
    }
})
